# Generated by Django 2.1.1 on 2018-11-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='achievements',
            old_name='Personid',
            new_name='PersonFullName',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='Categoryid',
        ),
        migrations.AddField(
            model_name='achievements',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
        migrations.AddField(
            model_name='achievmentdetails',
            name='AhievmentTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Achievements'),
        ),
        migrations.AddField(
            model_name='achievmentdetails',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
        migrations.AddField(
            model_name='achievmentdetails',
            name='PersonFullName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
    ]
