# Generated by Django 2.1.1 on 2018-11-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_person_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='CategoryName',
            new_name='Categoryid',
        ),
        migrations.RenameField(
            model_name='achievements',
            old_name='PersonFullName',
            new_name='Personid',
        ),
        migrations.RemoveField(
            model_name='achievmentdetails',
            name='AhievmentTitle',
        ),
        migrations.RemoveField(
            model_name='achievmentdetails',
            name='CategoryName',
        ),
        migrations.RemoveField(
            model_name='achievmentdetails',
            name='PersonFullName',
        ),
    ]
