# Generated by Django 2.1.1 on 2018-11-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181126_0252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AchievmentDetails',
        ),
        migrations.AddField(
            model_name='person',
            name='Gender',
            field=models.IntegerField(default=1),
        ),
    ]
